### PR TITLE
Fix detect link clicks to close sidebar

### PR DESCRIPTION
**Pull request by JumpLink**
Close sidebar on click link was not working for me (with jquery v1.12.2), in this way it works.

### CODE REVIEW

**Comment by dcdeiv** [comment]
Sorry but I have tested the unchanged lib with jquery v1.12.2 and it works. What isn't it working with yours? have you followed the instructions?

```
<a class="close-sidebar" href="#">Link</a>
<a href="#">Link</a>
<a class="close-sidebar" href="#">Link</a>
<a href="#">Link</a>

<element class="close-sidebar"></element>
```

and in the sidebar options:

`closingLinks: ".close-sidebar"` 

As it is written in the readme file:
> If you ignore this option, the plugin will look for all links and this can be buggy. Choose a class for every object inside the sidebar that once clicked will close the sidebar.

Basically if you ignore this option and you won't add a class to the link, it won't trigger the animation!

**Comment by JumpLink** [comment]
Okay you are right, this is not working with dynamic links.
Yes, I was following your instructions, probably my fault is elsewhere.
Is there a way to manually close the sidebar?

**Comment by dcdeiv** [comment]
You can close the sidebar by clicking on the button that opened it.
If the button is hidden by the sidebar, you have to work with the positioning. You can use the `top` option to lower the sidebar.

You can see a working example on the [static-right-top](https://github.com/dcdeiv/simpler-sidebar/blob/master/demo/static-right-top.html)

**Comment by JumpLink** [comment]
I mean to close the sidebar manually with javascript over any public function, is there a way?
I've found my mistake, it has nothing to do with your sidebar. Sorry for stealing your time.

**Comment by dcdeiv** [comment]
You are welcome!
Unfortunatelly there isn't one way yet, and I actually don't know how to add such a feature in this plugin yet!

I link you the issue still opened [here](https://github.com/dcdeiv/simpler-sidebar/issues/11)

**Pull request closed without merging**
